### ISSUE TITLE
Schema.org migration

### ISSUE THREAD

**Issue by lazybadger** [getgrav/grav-plugin-breadcrumbs#26]
Current schema for breadcumps is deprecated by Google
> data-vocabulary.org schema is deprecated and is no longer supported by Google. Please migrate to using schema.org types.

and will be ignored after April 2020. Consider movement to Schema.org

**Comment by ondrejvysek** [comment]
Check this including solution https://github.com/getgrav/grav-plugin-breadcrumbs/issues/25

**Comment by lazybadger** [comment]
Duplicate of #25
