### ISSUE TITLE
Has This Plugin Been Abandoned?

### ISSUE THREAD

**Issue by thekenshow** [getgrav/grav-plugin-breadcrumbs#30]
Given that Google [dropped support on April 6th](https://developers.google.com/search/docs/data-types/breadcrumb) for the markup used by this plugin, and that despite a fix [posted here on Jan 22](https://github.com/getgrav/grav-plugin-breadcrumbs/issues/25), should I assume this plugin is no longer supported?

**Comment by rhukster** [comment]
It's supported, but not often visited.  If a Pull Request is submitted, it stands a good chance to get merged and released.  I just have a hard time staying on top of over 200 repos that I currently am responsible for... Help is greatly appreciated.

**Comment by rhukster** [comment]
Actually just noticed that there were several commits pending a release including this one #29.. Just released as 1.6.0

**Comment by thekenshow** [comment]
Great, thanks for confirming and applying the change. Expecting nightmares tonight at the thought of 200 repos!
