### ISSUE TITLE
non-routable pages are included in breadcrumbs

### ISSUE THREAD

**Issue by danomatika** [getgrav/grav-plugin-breadcrumbs#5]
I have a simple site only using pages and I have a hierarchy that nests some folders with markdown files with organizational folders without markdown files. Currently, the plugin adds these non-routable folders in the breadcrumbs list.

The simple fix, which seems to be working for me, is to check routability before adding to the hierarchy array in `classes/breadcrumbs.php`:

    while($current && !$current->root()) {
         if($current->routable()) {
             $hierarchy[$current->url()] = $current;
         }
         $current = $current->parent();
     }

EDIT: Sorry for not making a PR. Being a bit lazy while working on the site. ;)

**Comment by rhukster** [comment]
as you are using these non-routable pages for categorization, wouldn't it make more sense to continue to add the pages, but don't make them linkable in the Twig? Ie, the whole route is displayed but you don't actually link, so can't reach the non-routable ones. 

Seems a better solution to me or your breadcrumbs are not going to reflect your structure as well.

**Comment by danomatika** [comment]
This site is basically a static class page site using grab, no blog or aggregate content.

The `user/pages` layout is basically like this:

    home
    home/home.md
    2015
    2015/fall
    2015/fall/class1
    2015/fall/class1/page.md
    2015/fall/class1/syllabus
    2015/fall/class1/syllabus/page.md
    2015/fall/class2
    2015/fall/class2/page.md
    2015/fall/class2/syllabus
    2015/fall/class2/syllabus/page.md
    2016/winter/class1
    2016/winter/class1/page.md
    2016/winter/class1/syllabus
    2016/winter/class1/syllabus/page.md
    2016/winter/class2
    2016/winter/class2/page.md
    2016/winter/class2/syllabus
    2016/winter/class2/syllabus/page.md

I'm started by putting the quarter & year info in the page title & initial content header. With my current solution, the bread crumbs for 2016/winter/class1/syllabus/page.md is:

    < Home < Class 1 Winter 2016 < Class 1 Syllabus

Note: I'm renaming the root page to "Home" in the breadcrumbs template.

You solution is

    < Home < 2016 < Winter < Class 1 < Syllabus

Which, indeed does look better. It hadn't occurred to me to not link the interim pages in the template, so I looked to remove them. I suppose I can change the breadcrumbs template to use the folder name and not the title, so I can keep the more descriptive titles (for bookmarks, etc). 

I understand the focus on always reflecting the user structure, however I can imagine a need, now and then, for using a more arbitrary structure. It seems like add a setting to allow/drop non routable pages could be useful, although off by default. Then again, it could be an edge case.

In any case, I'll rework the template a bit and see how it goes.

**Comment by rhukster** [comment]
Well the thing is you can easily override the breadcrumbs twig in your template, do make it do whatever you want.  So that would be the ideal solution.  You could skip the unroutable pages as you are doing currently, or you could make them unlinked.

But would just be an override for you and not any core breadcrumb plugin changes required.  I'll close this as I'm 100% sure you can do what you want from a template override alone :)

Thanks!

**Comment by danomatika** [comment]
Sure, thanks. This is also why I didn't make a PR :)

I initially took a crack at it in the template before modifying the plugin but didn't find the right info from the twig breadcrumb object. Looking at it now, is it something like:

    {% for crumb in crumbs %}
        {% crumb.routable %}
            ...

**Comment by rhukster** [comment]
should be yes.

**Comment by danomatika** [comment]
Is there api documentation? I looked at the breadcrumb class but there wasn't anything obvious to tell me what member variable I could get from the crumb object in the template. To be fair, I didn't follow the inheritance into Grav core.

**Comment by rhukster** [comment]
heh.. was just gonig to say :)  There is some automated docs, but they are pretty weak and need to be bolstered with more incode comments/docs:

http://learn.getgrav.org/api

**Comment by danomatika** [comment]
For future reference, here's my modified template:

~~~.php
{% set crumbs = breadcrumbs.get() %}
{% set breadcrumbs_config = config.plugins.breadcrumbs %}

{% if crumbs|length > 1 or breadcrumbs_config.show_all %}
<div id="breadcrumbs" itemscope itemtype="http://data-vocabulary.org/Breadcrumb">
{% for crumb in crumbs %}
    {% if not loop.last %}
        {% if crumb.url == base_url %}
            &lt; <a href="{{ base_url == '' ? '/' : base_url }}" itemprop="url"><span itemprop="title">Home</span></a>
        {% else %}
            {% if crumb.routable %}
                &lt; <a href="{{ crumb.url }}" itemprop="url"><span itemprop="title">{{ crumb.slug|titleize }}</span></a>
            {% else %}
                &lt; {{ crumb.menu }}
            {% endif %}
        {% endif %}
    {% endif %}
{% endfor %}
</div>
{% endif %}
~~~

"Home" is used for the root page and the titleized slug is used for routable pages since my page titles are generally more descriptive (i.e. longer).
